name: Docker_build_ubuntu

on:
  push:
    paths:
    - 'webapp/**'
    - 'dockerfile'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag k3nd0x/piglet:latest
    - uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_KEY }}
    - name: Push the image
      run: docker push k3nd0x/piglet:latest

  run-compose:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run the compose
      run: pwd && ls -al
