name: Docker_build_ubuntu

on:
  push:
    branches:
    - main
    paths:
    - 'webapp/**'
    - 'dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get latest release tag
        id: get_tag
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
      - name: Build the Docker image with latest release tag
        run: docker build . --file dockerfile --tag k3nd0x/piglet:${{ steps.get_tag.outputs.tag }}
      - name: Tag the image as latest
        run: docker tag k3nd0x/piglet:${{ steps.get_tag.outputs.tag }} k3nd0x/piglet:latest
      - uses: docker/login-action@v2
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_KEY }}
      - name: Push the image with latest release tag
        run: | 
          docker push k3nd0x/piglet:${{ steps.get_tag.outputs.tag }}
      - name: Push the image with latest tag
        run: |
          docker push k3nd0x/piglet:latest

  run-compose:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run the compose
      run: pwd && ls -al
