name: Docker_build_ubuntu

on:
  push:
    paths: 
    - 'webapp/**'
    - 'dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          RELEASE_VERSION=`git describe --tags --abbrev=0`

          DOCKER_IMAGE_TAG_RELEASE=k3nd0x/piglet:${RELEASE_VERSION}
          DOCKER_IMAGE_TAG_LATEST=k3nd0x/piglet:latest
          
          docker buildx build \
            --push \
            --tag $DOCKER_IMAGE_TAG_RELEASE \
            --file Dockerfile .
            
          docker push $DOCKER_IMAGE_TAG_RELEASE
          
          # Tag and push the Docker image with latest tag
          docker tag $DOCKER_IMAGE_TAG_RELEASE $DOCKER_IMAGE_TAG_LATEST
          docker push $DOCKER_IMAGE_TAG_LATEST
      
  run-compose:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Run the compose
      run: pwd && ls -al
