name: run_compose
needs: Docker_build_ubuntu
on:
  push:
    paths: 
    - 'webapp/**'
    - 'dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run the compose file
      run: docker-compose up -d 
      
